### ISSUE TITLE
Trial SA

### ISSUE THREAD

**Issue by DaBoyTM** [AlexFreedomMod/ZaramaFreedomMod#11]
I was thinking maybe (with Zarama approval) We should change Trial SA to Admin

**Comment by AlexFreedomMod** [comment]
Ok

**Comment by AlexFreedomMod** [comment]
Zarama hadn't come in like 10 years

**Comment by AlexFreedomMod** [comment]
The rank was useless anyways ;

**Comment by AlexFreedomMod** [comment]
Thanks, @DaBoyTM. Very helpful to remove a Un-used rank!
